# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32b022a3ce60faf83d96194268d4e7bf3bf7549400894666f49bf192ba297c83c3e34027b0b8ef2e83c533bb56fc8369ec9204a04f581d2cfbd944dfe0598b8c

test:
  secret_key_base: 6546a1c26e9212127f331acadcacf394d84a4beddc6937f1b369689ff04bf55efbfd13950acd77ad78fb8e1532f9286d72f0a12e4451dd31fd948954911bee4d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
